import { useMemo, useState } from 'react'
import { MARKET_LISTINGS, createMyListing, loadMyListings, marketCategories, removeMyListing } from '../services/marketService'
import type { MarketListing, NavProps, WardrobeCategory, WardrobeItem } from '../types'

interface Props extends NavProps {
  initialCategory?: WardrobeCategory
  initialColor?: string
  items: WardrobeItem[]
  listingItem?: WardrobeItem
  onCompleteListing: (listing: MarketListing) => void
}

export default function MarketScreen({ onNavigate, initialCategory, initialColor, items, listingItem, onCompleteListing }: Props) {
  const [category, setCategory] = useState<WardrobeCategory | 'all'>(initialCategory ?? 'all')
  const [mode, setMode] = useState<'all' | 'buy' | 'trade'>('all')
  const [selected, setSelected] = useState<MarketListing | null>(null)
  const [draft, setDraft] = useState<WardrobeItem | null>(listingItem ?? null)
  const [choosingItem, setChoosingItem] = useState(false)
  const [listingType, setListingType] = useState<MarketListing['listingType'] | null>(listingItem ? null : null)
  const [price, setPrice] = useState('20')
  const [size, setSize] = useState(listingItem?.size ?? '')
  const [condition, setCondition] = useState('Good condition')
  const [tradePreference, setTradePreference] = useState('Open to offers')
  const [notice, setNotice] = useState('')
  const [revision, setRevision] = useState(0)
  const [confirmCompletion, setConfirmCompletion] = useState<MarketListing | null>(null)
  const mine = useMemo(() => loadMyListings(), [revision])
  const listings = useMemo(() => [...mine, ...MARKET_LISTINGS].filter(listing => (category === 'all' || listing.category === category) && (mode === 'all' || listing.listingType === mode)).sort((a, b) => Number(Boolean(initialColor && a.color === initialColor)) - Number(Boolean(initialColor && b.color === initialColor))).reverse(), [mine, category, mode, initialColor])
  const sendRequest = () => { if (!selected) return; setNotice(selected.listingType === 'trade' ? 'Trade request sent — this is a local demo.' : `Request sent to ${selected.sellerName} — this is a local demo.`); setSelected(null) }
  const saveListing = () => {
    if (!draft || !listingType) return
    const existing = mine.find(listing => listing.wardrobeItemId === draft.id)
    if (existing) { setNotice('Already listed on WE-AR Market.'); setDraft(null); setListingType(null); return }
    createMyListing(draft, listingType, { price: listingType === 'buy' ? Number(price) || undefined : undefined, size: size || draft.size || 'One size', condition, tradePreference: listingType === 'trade' ? tradePreference : undefined })
    setNotice(listingType === 'trade' ? 'Listed for trade. Your item is still in your wardrobe.' : 'Listed on WE-AR Market. Your item is still in your wardrobe.')
    setDraft(null); setListingType(null); setRevision(value => value + 1)
  }
  const closeDraft = () => { setDraft(null); setListingType(null) }
  return <div className="bg-[#f7f5f2] min-h-screen pb-10"><div className="h-12"/><div className="px-5">
    <button onClick={() => onNavigate('home')} className="text-[#888] text-sm mb-5">← Back</button>
    <div className="flex items-start justify-between gap-3"><div><h1 className="text-[30px] font-bold mb-1">WE-AR Market</h1><p className="text-[#888] text-sm mb-5">Keep clothes in circulation.</p></div><button onClick={() => { setDraft(null); setListingType(null); setChoosingItem(true) }} className="bg-[#111] text-white text-xs font-bold px-3 py-2 rounded-full">+ List an Item</button></div>
    <div className="bg-[#1b4332] text-white rounded-[20px] p-4 mb-5"><p className="font-bold">Secondhand first</p><p className="text-xs text-white/75 mt-1">Buy secondhand, trade what you own, or give pieces a new home.</p></div>
    {notice && <div className="bg-[#fef9ec] border border-[#f0d98a] rounded-xl p-3 text-sm text-[#8a6200] mb-4">✓ {notice}</div>}
    {mine.length > 0 && <div className="mb-5"><p className="text-[10px] font-bold tracking-[.12em] text-[#999] mb-2">MY LISTINGS</p><div className="space-y-2">{mine.map(listing => <div key={listing.id} className="bg-white border border-[#edebe6] rounded-2xl p-3 flex gap-3"><img src={listing.image} alt="" className="size-14 object-contain bg-[#faf9f6] rounded-xl p-1"/><div className="min-w-0 flex-1"><p className="font-semibold text-sm truncate">{listing.title}</p><p className="text-[10px] font-bold text-[#1b4332] mt-0.5">{listing.listingType === 'trade' ? 'FOR TRADE' : `FOR SALE · $${listing.price}`}</p><p className="text-[10px] text-[#888] mt-0.5">{listing.listingType === 'trade' ? `Looking for: ${listing.tradePreference}` : 'Active listing'}</p></div><div className="flex flex-col items-end gap-1"><button onClick={() => setConfirmCompletion(listing)} className="text-[10px] font-bold text-[#1b4332]">{listing.listingType === 'trade' ? 'Mark as Traded' : 'Mark as Sold'}</button><button onClick={() => { removeMyListing(listing.id); setRevision(value => value + 1); setNotice('Listing removed. Your wardrobe item is unchanged.') }} className="text-[10px] text-[#a33]">Remove Listing</button></div></div>)}</div></div>}
    <div className="flex gap-2 mb-3"><button onClick={() => setMode('all')} className={`flex-1 rounded-xl py-2 text-sm font-bold ${mode === 'all' ? 'bg-[#111] text-white' : 'bg-white border border-[#edebe6]'}`}>All</button><button onClick={() => setMode('buy')} className={`flex-1 rounded-xl py-2 text-sm font-bold ${mode === 'buy' ? 'bg-[#111] text-white' : 'bg-white border border-[#edebe6]'}`}>Buy</button><button onClick={() => setMode('trade')} className={`flex-1 rounded-xl py-2 text-sm font-bold ${mode === 'trade' ? 'bg-[#111] text-white' : 'bg-white border border-[#edebe6]'}`}>Trade</button></div>
    <div className="flex gap-2 overflow-x-auto mb-5 pb-1">{marketCategories.map(item => <button key={item.value} onClick={() => setCategory(item.value)} className={`shrink-0 px-3 py-1.5 rounded-full text-xs font-semibold ${category === item.value ? 'bg-[#1b4332] text-white' : 'bg-white border border-[#edebe6] text-[#666]'}`}>{item.label}</button>)}</div>
    <div className="grid grid-cols-2 gap-3">{listings.map(listing => <button key={listing.id} onClick={() => setSelected(listing)} className="bg-white border border-[#edebe6] rounded-[20px] overflow-hidden text-left"><div className="aspect-square bg-[#faf9f6] flex items-center justify-center p-3"><img src={listing.image} alt={listing.title} className="max-h-28 object-contain"/></div><div className="p-3"><div className="flex justify-between gap-1"><p className="font-semibold text-[12px] leading-tight">{listing.title}</p><span className="text-[10px] font-bold text-[#1b4332]">{listing.listingType === 'trade' ? 'Trade' : `$${listing.price}`}</span></div><p className="text-[10px] text-[#888] mt-1">{listing.size} · {listing.condition}</p><p className="text-[10px] text-[#aaa] mt-1">{listing.isMine ? 'Your listing' : listing.sellerName}</p></div></button>)}</div>
    {choosingItem && <div className="fixed inset-0 z-40 bg-black/40 flex items-end justify-center"><div className="w-full max-w-[430px] bg-[#f7f5f2] rounded-t-[28px] p-5"><p className="font-bold text-lg">List an Item</p><p className="text-xs text-[#888] mt-1">Choose an active wardrobe piece to list.</p><div className="grid grid-cols-3 gap-2 mt-4 max-h-64 overflow-y-auto">{items.filter(item => item.isActive !== false).map(item => <button key={item.id} onClick={() => { setDraft(item); setChoosingItem(false) }} className="bg-white border border-[#edebe6] rounded-xl p-2 text-center"><img src={item.image} alt="" className="h-12 w-full object-contain"/><p className="text-[10px] font-semibold truncate mt-1">{item.name}</p></button>)}</div><button onClick={() => setChoosingItem(false)} className="w-full py-3 text-sm text-[#888]">Cancel</button></div></div>}
    {draft && !listingType && <div className="fixed inset-0 z-40 bg-black/40 flex items-end justify-center"><div className="w-full max-w-[430px] bg-[#f7f5f2] rounded-t-[28px] p-5"><p className="font-bold text-lg">How would you like to list it?</p><div className="flex gap-2 mt-4"><button onClick={() => setListingType('buy')} className="flex-1 bg-[#1b4332] text-white rounded-2xl py-3 font-bold">Sell</button><button onClick={() => setListingType('trade')} className="flex-1 bg-white border border-[#edebe6] rounded-2xl py-3 font-bold">Trade</button></div><button onClick={closeDraft} className="w-full py-3 text-sm text-[#888]">Cancel</button></div></div>}
    {draft && listingType && <div className="fixed inset-0 z-50 bg-black/40 flex items-end justify-center"><div className="w-full max-w-[430px] bg-[#f7f5f2] rounded-t-[28px] p-5"><p className="font-bold text-lg">{listingType === 'buy' ? 'List for Sale' : 'List for Trade'}</p><div className="flex gap-3 mt-3"><img src={draft.image} alt="" className="size-14 bg-white rounded-xl object-contain"/><div><p className="font-semibold text-sm">{draft.name}</p><p className="text-xs text-[#888] capitalize">{draft.category}{draft.color ? ` · ${draft.color}` : ''}</p></div></div><div className="grid grid-cols-2 gap-2 mt-4">{listingType === 'buy' && <label className="text-xs text-[#666]">Price<input value={price} onChange={event => setPrice(event.target.value)} inputMode="numeric" className="mt-1 w-full bg-white border border-[#edebe6] rounded-xl p-2"/></label>}<label className="text-xs text-[#666]">Size<input value={size} onChange={event => setSize(event.target.value)} placeholder="e.g. M" className="mt-1 w-full bg-white border border-[#edebe6] rounded-xl p-2"/></label><label className="text-xs text-[#666]">Condition<input value={condition} onChange={event => setCondition(event.target.value)} className="mt-1 w-full bg-white border border-[#edebe6] rounded-xl p-2"/></label>{listingType === 'trade' && <label className="col-span-2 text-xs text-[#666]">Looking for<input value={tradePreference} onChange={event => setTradePreference(event.target.value)} className="mt-1 w-full bg-white border border-[#edebe6] rounded-xl p-2"/></label>}</div><button onClick={saveListing} className="w-full mt-5 bg-[#1b4332] text-white rounded-2xl py-3.5 font-bold">{listingType === 'buy' ? 'List for Sale' : 'List for Trade'}</button><button onClick={closeDraft} className="w-full py-3 text-sm text-[#888]">Cancel</button></div></div>}
    {selected && <div className="fixed inset-0 z-50 bg-black/40 flex items-end justify-center" onClick={() => setSelected(null)}><div className="w-full max-w-[430px] bg-[#f7f5f2] rounded-t-[28px] p-5" onClick={event => event.stopPropagation()}><p className="font-bold text-lg">{selected.title}</p><p className="text-sm text-[#1b4332] font-bold mt-1">{selected.listingType === 'trade' ? 'Open to trade' : `$${selected.price}`}</p><p className="text-sm text-[#666] mt-4">{selected.description}</p><button onClick={sendRequest} className="w-full mt-5 bg-[#1b4332] text-white rounded-2xl py-3.5 font-bold text-sm">{selected.listingType === 'trade' ? 'Offer Trade' : 'Buy Secondhand'}</button><button onClick={() => setSelected(null)} className="w-full py-3 text-sm text-[#888]">Close</button></div></div>}
    {confirmCompletion && <div className="fixed inset-0 z-[60] bg-black/40 flex items-center justify-center px-5"><div className="bg-white rounded-[24px] p-6 text-center max-w-[330px]"><p className="font-bold text-lg">{confirmCompletion.listingType === 'trade' ? 'Mark as traded?' : 'Mark as sold?'}</p><p className="text-sm text-[#777] mt-2">{confirmCompletion.listingType === 'trade' ? "Confirm only after you've completed the exchange." : 'Confirm only after this item has found a new owner.'}</p><div className="flex gap-2 mt-5"><button onClick={() => setConfirmCompletion(null)} className="flex-1 border border-[#ddd] rounded-xl py-3 text-sm font-semibold">Not yet</button><button onClick={() => { onCompleteListing(confirmCompletion); removeMyListing(confirmCompletion.id); setConfirmCompletion(null); setRevision(value => value + 1) }} className="flex-1 bg-[#1b4332] text-white rounded-xl py-3 text-sm font-bold">{confirmCompletion.listingType === 'trade' ? 'Mark as traded' : 'Mark as sold'}</button></div></div></div>}
  </div></div>
}
